spring:
  application:
    name: myblog
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/myblog
    username: user
    password: pass
    type: com.zaxxer.hikari.HikariDataSource
  sql:
    init:
      mode: always