version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: postgres_myblog
    environment:
      POSTGRES_DB: myblog
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf

volumes:
  pgdata: